export const productsData = [
  {
    id: 1,
    name: "Massage Gun",
    description: "High-powered muscle relaxation tool",
    price: 249.99,
    imageUrl: "/foamroller.jpg",
  },
  {
    id: 2,
    name: "Massage Gun",
    description: "High-powered muscle relaxation tool",
    price: 250.99,
    imageUrl: "/foamroller.jpg",
  },
  {
    id: 3,
    name: "Massage Gun",
    description: "High-powered muscle relaxation tool",
    price: 250.99,
    imageUrl: "/foamroller.jpg",
  },
  {
    id: 4,
    name: "Massage Gun",
    description: "High-powered muscle relaxation tool",
    price: 250.99,
    imageUrl: "/foamroller.jpg",
  },
  {
    id: 5,
    name: "Massage Gun",
    description: "High-powered muscle relaxation tool",
    price: 250.99,
    imageUrl: "/foamroller.jpg",
  },
  {
    id: 6,
    name: "Massage Gun",
    description: "High-powered muscle relaxation tool",
    price: 250.99,
    imageUrl: "/foamroller.jpg",
  },
  {
    id: 7,
    name: "Massage Gun",
    description: "High-powered muscle relaxation tool",
    price: 250.99,
    imageUrl: "/foamroller.jpg",
  },
];
